### ISSUE TITLE
why i change the video it tells :TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by host452b** [kimyoon-young/centerNet-deep-sort#10]
detections = [Detection(bbox_xywh[i], conf, features[i]) for i,conf in enumerate(confidences)]
TypeError: 'NoneType' object is not iterable

**Comment by kimyoon-young** [comment]
Hi. 
This error occurs when there is no person in a image.
So I added error handling code.

https://github.com/kimyoon-young/centerNet-deep-sort/blob/e6cb4a63c78eb0c1e47202480d6e2f44293864c2/demo_centernet_deepsort_thread.py#L115

Thanks

**Comment by host452b** [comment]
If I want to track as many goals as possible, avoid the problem of automatically exiting the target without the corresponding tracking in the video? How to solve
please tell me ~thanks~

**Comment by Muhtasham** [comment]
@Clemente420 Have you find a way of not losing the target in the video?
