### ISSUE TITLE
run demo error

### ISSUE THREAD

**Issue by CompliceU** [kimyoon-young/centerNet-deep-sort#2]
ModuleNotFoundError: No module named '_init_paths',plz guide me,thx

**Comment by kimyoon-young** [comment]
Sorry, I didn't comment 'import _init_paths' in exdet.py
I have just finished modification.

**Comment by kimyoon-young** [comment]
> ModuleNotFoundError: No module named '_init_paths',plz guide me,thx

Sorry, I didn't comment 'import _init_paths' in exdet.py
I have just finished modification.
