### ISSUE TITLE
RGB BGR conversion

### ISSUE THREAD

**Issue by fabbrimatteo** [kimyoon-young/centerNet-deep-sort#3]
I think you need to convert BGR to RGB before feeding the network. Here:

https://github.com/kimyoon-young/centerNet-deep-sort/blob/aaa0e21e6d56af9f11a9f4a51a69d2dd0e1325e0/demo_centernet_deepsort.py#L67

**Comment by kimyoon-young** [comment]
You are right. I modified that line.
Thank you!
