### ISSUE TITLE
any plan to upgrade to PyTorch 1.0?

### ISSUE THREAD

**Issue by rambleramble** [kimyoon-young/centerNet-deep-sort#4]
The reason of this request is that following error:

"raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
 ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead."

Also,  some other detectors such as Mask-RCNN is also supported by PyToch1.0.

Thanks

**Comment by kimyoon-young** [comment]
Hi. thank you for your suggestion I'll try that!
